#pragma once

int ScoreBoard[]={0,0,0,0,0,0,0};

const PROGMEM SaveDefault savefileDefaults[] = {
  { 0,SAVETYPE_INT,0,0 },
  { 1,SAVETYPE_INT,0,0 },
  { 2,SAVETYPE_INT,0,0 },
  { 3,SAVETYPE_INT,0,0 },
  { 4,SAVETYPE_INT,0,0 },
  { 5,SAVETYPE_INT,0,0 },
  { 6,SAVETYPE_INT,0,0 }
};

const PROGMEM unsigned int TileSelectionBoard[7] = { 0, 0, 0, 0, 0, 0, 0 };
const PROGMEM unsigned int TileSelectionUp[7] = { CORRIDOR_CROSSROADS, CORRIDOR_STRAIGHT_VERTICAL, CORRIDOR_TURN_DOWN_LEFT, CORRIDOR_TURN_DOWN_RIGHT, CORRIDOR_STRAIGHT_VERTICAL_LEFT, CORRIDOR_STRAIGHT_VERTICAL_RIGHT, CORRIDOR_STRAIGHT_HORIZONTAL_DOWN };
const PROGMEM unsigned int TileSelectionDown[7] = { CORRIDOR_CROSSROADS, CORRIDOR_STRAIGHT_VERTICAL, CORRIDOR_TURN_UP_LEFT, CORRIDOR_TURN_UP_RIGHT, CORRIDOR_STRAIGHT_VERTICAL_LEFT, CORRIDOR_STRAIGHT_VERTICAL_RIGHT, CORRIDOR_STRAIGHT_HORIZONTAL_UP };
const PROGMEM unsigned int TileSelectionLeft[7] = { CORRIDOR_CROSSROADS, CORRIDOR_STRAIGHT_HORIZONTAL, CORRIDOR_TURN_UP_RIGHT, CORRIDOR_TURN_DOWN_RIGHT, CORRIDOR_STRAIGHT_VERTICAL_RIGHT, CORRIDOR_STRAIGHT_HORIZONTAL_DOWN, CORRIDOR_STRAIGHT_HORIZONTAL_UP };
const PROGMEM unsigned int TileSelectionRight[7] = { CORRIDOR_CROSSROADS, CORRIDOR_STRAIGHT_HORIZONTAL, CORRIDOR_TURN_UP_LEFT, CORRIDOR_TURN_DOWN_LEFT, CORRIDOR_STRAIGHT_VERTICAL_LEFT, CORRIDOR_STRAIGHT_HORIZONTAL_DOWN, CORRIDOR_STRAIGHT_HORIZONTAL_UP };
const PROGMEM unsigned int TileEventBoard[8] = { TILE_EVENT_TREASURE, TILE_EVENT_SNAKES, TILE_EVENT_BARS, TILE_EVENT_TREASURE, TILE_EVENT_MUMMY, TILE_EVENT_TRAP, TILE_EVENT_HIEROGLYPHICS, TILE_EVENT_TREASURE };
